import type { Metadata } from "next";
import Link from "next/link";
import { Photo } from "@/components/photo";
import { Arrow } from "@/components/icons";

export const metadata: Metadata = { title: "Our story", description: "Natural Kitchen began on Marylebone High Street in 2009. Discover our all-day approach to freshly prepared food, good ingredients and welcoming London spaces.", alternates: { canonical: "/about/" } };
export default function AboutPage() {
  return <><section className="venue-hero about-hero"><div className="venue-hero-copy"><p className="eyebrow">A LITTLE ABOUT US</p><h1>More than a meal.<br /><em>A moment together.</em></h1><p>Natural Kitchen began on Marylebone High Street in 2009, with a simple idea: freshly prepared food and a welcoming place to enjoy it, throughout the day.</p></div><Photo name="trinity-square" alt="Guests enjoying Natural Kitchen’s welcoming restaurant space" priority /></section><section className="container story-section"><p className="eyebrow">GOOD FOOD. GOOD PEOPLE.</p><div><h2>Made with care.<br /><em>Shared with company.</em></h2><p>Breakfast before a busy day. A catch-up over lunch. A drink with friends. We bring restaurants, bars and food-to-go delis together, with something for every kind of visit.</p><p>Our kitchens prepare food daily. We choose producers who care about flavour, quality, provenance and traceability, with the environment in mind.</p><p>From organic coffee and fresh juices to seasonal dishes, it’s food to enjoy at your own pace. Pull up a chair. You’re in good company.</p><Link className="text-link" href="/restaurants/">Find your Natural Kitchen <Arrow /></Link></div></section><section className="about-photo-strip"><Photo name="breakfast" alt="Breakfast at Natural Kitchen" /><Photo name="smoothies" alt="Fresh smoothies" /><Photo name="seasonal-food" alt="Freshly prepared food" /></section><section className="container simple-cta"><h2>Your day, <em>made a little better.</em></h2><Link className="button" href="/menus/">Find your favourite <Arrow /></Link></section></>;
}
