import type { Metadata } from "next";
import { Photo } from "@/components/photo";
import { Arrow } from "@/components/icons";
import { CateringEnquiry } from "@/components/catering-enquiry";

export const metadata: Metadata = { title: "Catering & private events", description: "Plan office catering, private celebrations and venue hire with Natural Kitchen in London.", alternates: { canonical: "/catering/" } };
export default function CateringPage() {
  return <><section className="venue-hero"><div className="venue-hero-copy"><p className="eyebrow">CATERING & PRIVATE EVENTS</p><h1>Bring your people.<br /><em>We’ll bring the food.</em></h1><p>From a dinner for ten to drinks and finger food for a crowd, let’s make getting together feel effortless.</p><a href="#enquire" className="button">Tell us your plans <Arrow /></a></div><Photo name="angel-court" alt="Natural Kitchen Angel Court’s spacious restaurant and bar" priority /></section><section className="container occasion-grid"><article><span className="eyebrow">01 · AT THE OFFICE</span><h2>A better working lunch.</h2><p>Freshly prepared food to keep your team, clients and guests in good company. Ask us about collection and delivery.</p></article><article><span className="eyebrow">02 · YOUR OCCASION</span><h2>A reason to celebrate.</h2><p>A birthday, a gathering, or simply getting everyone together. We can bring the food to you.</p></article><article><span className="eyebrow">03 · OUR PLACE</span><h2>Make yourself at home.</h2><p>Host your event in one of our central London venues. Talk to us about private hire and the space you need.</p></article></section><section className="enquiry-section" id="enquire"><div className="container enquiry-layout"><div><p className="eyebrow">LET’S PLAN SOMETHING</p><h2>Good things start<br /><em>with a conversation.</em></h2><p>Tell us what you have in mind.<br />Our team will help with the rest.</p><a href="tel:+442073748531">020 7374 8531</a><a href="mailto:info@naturalkitchen.co.uk">info@naturalkitchen.co.uk</a></div><CateringEnquiry /></div></section></>;
}
